;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./src/
default_envs = esp8266
description = The Microsoft Teams Neopixel Presence Device for ESP8266

[env]
framework=arduino
monitor_speed=115200
upload_speed=921600
build_flags=
    -DDATAPIN=2
    -DNUMLEDS=16
    ; -DCORE_DEBUG_LEVEL=5
lib_deps=
  IotWebConf@2.3.3
  ArduinoJson@6.21.0
  Adafruit NeoPixel@^1.12.0

[env:esp8266]
platform=espressif8266
board=nodemcuv2

[env:esp8266-nocertcheck]
platform=espressif8266
board=nodemcuv2
build_flags=
    ${env.build_flags}
    -DDISABLECERTCHECK